### ISSUE TITLE
Add Mummy the Resurrection

### ISSUE THREAD

**Issue by JohanFalt** [JohanFalt/Foundry_WoD20#140]

**Comment by andersonalmeidda** [comment]
it would be very interesting, it would make it very complete ... because even on other platforms there is no charactersheet for this and this game is incredible

**Comment by JohanFalt** [comment]
It is Mummy and Wraith left to be made, other things has just kept them being pushed forward. I'll place Mummy in the cue and then we see exactly what version I add it.

**Comment by andersonalmeidda** [comment]
I think the latest edition is the most interesting, most playable as well. I run a table but use a mortal character sheet and we mark the Sekhem and Hekau Balance in the notes, we also do manual rolls. It would be really awesome to have a Mummy Character Sheet. Thanks for the feedback! Wow if Wraith the Oblivion (I would GM this, people on my live stream would love it since they love horror, gothic) over time it would indeed be the most complete system in the foundry, congratulations!!

**Comment by JaoSathler96** [comment]
Woooow Mummy and Wraith would be nice, I play both with my friends and we use a PDF, but a plug for these systems would be very nice haha
