### ISSUE TITLE
Other Changelings

### ISSUE THREAD

**Issue by Ringelpiez** [JohanFalt/Foundry_WoD20#273]
- [x] https://github.com/JohanFalt/Foundry_WoD20/issues/667
- [x] https://github.com/JohanFalt/Foundry_WoD20/issues/668
- [x] https://github.com/JohanFalt/Foundry_WoD20/issues/669
- [x] https://github.com/JohanFalt/Foundry_WoD20/issues/670
- [x] https://github.com/JohanFalt/Foundry_WoD20/issues/671
- [x] https://github.com/JohanFalt/Foundry_WoD20/issues/672
- [ ] https://github.com/JohanFalt/Foundry_WoD20/issues/673
- [x] https://github.com/JohanFalt/Foundry_WoD20/issues/612

I'll see what else it would take to build anything other than Kithain. Simply because I feel like it. :)

Even if other terms are used:

**Dauntain**
- Check

**Thallain**
- Check

**Dark Kin**
Kith - Check
Seeming (change regularly)
Legacy (each depending on the Seeming)
Birthright/Frailty - Check

**Nunnehi**
- Check

**Menehune**
- Check

**Hsien**
several things would have to be changed for this.

**Inanimae**
- Check

**Other Kiths**
- Check

**Comment by JohanFalt** [comment]
What is missing with those and where can I read about them? Are they all in the main book?

**Comment by Ringelpiez** [comment]
Yes, all in the C20 Core.
But they are certainly used much less frequently by the community than the normal Changelings (Kithain).

- Only the designations are often different. Inanimae don't have Seelie/Unseelie as their court, they have Gladling/Krofted.
- For others, the "upper designation" also changes. Instead of Seeming (Childling/Wilder/Grump), Dark-Kin have something called Aria (Dioniae/Araminae/Apolliae).
- It is most extreme with the Hsien, as they are based on Asian mythology/culture. For example, there is no glamor but Wu-Tan.

But I don't think this topic is that important.
Dauntain, Thallian and possibly Dark-Kin are classic antagonists and should appear more often. I think.

**Comment by EldritchTranslator** [comment]
If you want the pages:
- Dauntain, p.359: Basically Changelings, they have a curse on them that should be written somewhere, but apart from that they're identical;
- Thallain, p.368: Their sheet has the same structure as the Changeling one, but they have different Seemings (Perturbed, Prowler, and Miser), they have two Legacies (one Nightmare and one normal one), their Birthright is called Endowment and Frailties are Vulnerabilities, and I think that's it;
- Dark-Kin, p. 383: They're a bit different, since they don't have Banality, they have different Seemings, called Arià (Dioniae, Araminae, Apolliae, as said above), and their Kiths are called Adhene, which have Birthright and Frailties like Changelings.

There are also these Non-Changeling fae, which should be fairly rare to find in games:
- Nunnehi, p. 394: Native american fae, they have three 'Camps' instead of Courts (Summer, Winter, Midseason), as well as Summer and Winter Legacies, but apart from that their Kiths are structured the same as Changelings. They call Glamour 'Medicine', and don't have a Threshold. They have also access to a Background called 'Totem', which is exactly like the Werewolf one with a Trait/benefit and a Taboo.
- Menehune, p.411: Native Hawai'ian fae; they have two Camps, Feast and War, which also name the Legacies; their Kiths are called Callings, but work the same; they also have totems. They call Glamour 'Mana', and don't have a Threshold.
- Inanimae, p.437: They have two Courts, Gladeling and Krofted. I don't think they have Thresholds. They have Kiths called Phyla, and they have Slivers instead of Arts, and each Phyla has an Affinity Sliver. They are divided in five levels but don't have singular powers.

Then there are the Hsien, p.421: Asian... spirit fae. 
They are different from all the above. They do not have Glamour or Banality, to power their spells they have the Yugen, which has temporary and permanent values. They have a number of Courts, and their legacies are Yin and Yang. They have a Rank. They don't have Seemings, but two groups (Kannon-jin), the Hirayanu and Kamui, each divided in various 'kiths'.  They also have different Abilities, with Leadership as a Talent, Gremayre is back to Occult, and they have Shentao instead of Kenning. Their Kiths have Luck and Curses instead of Birthrights and Frailties. 

Like I said above, their Tempers are different; they have Willpower, of course, but they have Chi, divided in Yin and Yang, and that has a level between 1 and 5. Then they have the Tao, a value that's the average of Yin and Yang Chi. 

They don't have Arts and Realms, but they have a sacred alchemy called Wu Tan, divided in I Chih and Nei Tan, with five levels of proficiency each. Their casting is much more complex modifier-wise than Arts, and may need something similar to the Mage casting (if one wants to automate that obvs). I actually don't understand it well, but in the I Chih there are various different effects each level, and it probably has something to do with the five elements. The Nei Tan are other five levels, but they have to roll their Tao + one of their Abilities, or Attributes, or even Backgrounds to activate them... plus the modifiers, of course.

A sheet that may work as a visual example is [https://mrgone.rocksolidshells.com/pdf/C20/C20_1-Page_Shinma-Hsien-Landof8milliondreams_Interactive.pdf](THIS), even though it is NOT C20.

They exist, but I have never, ever heard anyone using them, especially not in a Changeling game, so... maybe don't prioritize them much?

**Comment by Ringelpiez** [comment]
Better and properly summarized. I totally agree.
(With the little difference that I've seen Inanimae as PCs more than once.)

**Comment by EldritchTranslator** [comment]
> Better and properly summarized. I totally agree. (With the little difference that I've seen Inanimae as PCs more than once.)

Thank you. The 'I have never seen them' was related to the Hsien; I have personally used Inanimae quite a bit as well as Dark-Kin, Dauntain, and Thallain. Still, I don't think that any of these should be 'first CtD release' priority, since it's still a bit of data to create for the sheets, even the easier ones.

**Comment by JohanFalt** [comment]
I’ll focus on the main Changelings for this version, and then handle the others like I did with Changing Breeds to Werewolf.

**Comment by JohanFalt** [comment]
For v1.7 I'll add normal Changelings and Dauntain.

**Comment by ovidianskin** [comment]
I'm adding two character sheets we used for C20 for Dark-kin and Hsien. 

I'm fairly certain the Hsien one is an updated version.  

Yeah, i have both in my current 3 year game.  My game design criticism of the hsien aside, the system is pretty awesome but also kinda broad.  

Hsien don't have the enchanted damage meter, so that's a thing I'd like to be an option attachment ot a character sheet.  I worked around it by handwaving some of the vague rulebook text and also haveing an artifact that keeps the character enchanted, which is...soimething else, but having chimerical damage would be helpfuil.

However, it's not shown as written, so I woulnd't be annoyed if you did not incorporate "add on" Chimerical Damage levels.  

Below are links to a Dark-kin 4 Page sheet of the fill in variety, and a 4 page C20 Hsien sheet we use.  Let me know fi there are issues:

- [Denizens of the Dreaming V2 4 page](https://drive.google.com/file/d/1RCxs9HkPo0n7RoQ_tETrhV4VN30XuGH_/view?usp=drive_link)
- [Shinma Hsien 4 page ](https://drive.google.com/file/d/1D7WfgEWJhTEv_6Cg8mkbDjnHKtW0zelg/view?usp=drive_link)

**Comment by JohanFalt** [comment]
I'll move this to the next version. I'll need to analys and read more about the other types of Changelings before I go into this. I'll change the plans for v3.2 accordingly.

**Comment by JohanFalt** [comment]
- [ ] https://github.com/JohanFalt/Foundry_WoD20/issues/667
- [ ] https://github.com/JohanFalt/Foundry_WoD20/issues/668
- [ ] https://github.com/JohanFalt/Foundry_WoD20/issues/669
- [ ] https://github.com/JohanFalt/Foundry_WoD20/issues/670
- [ ] https://github.com/JohanFalt/Foundry_WoD20/issues/671
- [ ] https://github.com/JohanFalt/Foundry_WoD20/issues/672
- [ ] https://github.com/JohanFalt/Foundry_WoD20/issues/673
- [ ]

**Comment by JohanFalt** [comment]
Will not implement Hsien at this stage. Instead if you wish to use them then you will need to use the creature sheet.
