### ISSUE TITLE
VtM V20 Can't add different paths

### ISSUE THREAD

**Issue by Lachrimae93** [JohanFalt/Foundry_WoD20#277]
Can you allow user input for the paths if we want to run a game that has all the other paths that you didn't include? (Like the path of harmony for example).

**Comment by JohanFalt** [comment]
This will be fixed in the coming version described initially here:

**Comment by Lachrimae93** [comment]
any idea which version this will be applicable to? Just typing the path/road I think should be simple?

**Comment by JohanFalt** [comment]
Not in 2.3 at least. The biggest problem with this issue is that it is not just to make the Path value customizable out of a hat as the value of it desides other values of the sheet, mainly virtues. 
The plan is to make the rest of the sheets done first then I'll start to look at how to implement stuff like this. But as I said, v2.4 at the earliest.

**Comment by Lachrimae93** [comment]
I don't see the issue with changing values. The only thing the path changes is the virtues and that is a binary change. If you're humanity, it's one value. If you're anything else at all, it's the other value. Those are the only two choices.
