### ISSUE TITLE
System Update seems to reset Humanity (Vampire sheet)

### ISSUE THREAD

**Issue by Havoclivekiller** [JohanFalt/Foundry_WoD20#594]
Like the title, the second time after a system update all my sheets have their Humanity set to 0.

**Comment by JohanFalt** [comment]
What version did you upgrade from?

**Comment by EldritchTranslator** [comment]
Happened to me too, upgrading from v 2.4 to 3.0 while staying on Foundry v10.

**Comment by Havoclivekiller** [comment]
I think the first one was 2.4.9 to 2.4.10, then 2.4.10 to 3.0.

**Comment by JohanFalt** [comment]
Can you with a vampire that hasn't been fixed for this, open the sheet up. Press F12 and take a screen dump on how the inner data looks as I have done with this one:

![image](https://github.com/JohanFalt/Foundry_WoD20/assets/57871596/3d1fdbdd-80d1-4ed2-965b-72d2da20624c)

**Comment by Havoclivekiller** [comment]
![image](https://github.com/JohanFalt/Foundry_WoD20/assets/21118924/be2f1e4f-8add-42ab-94b2-7f57d687b950)

**Comment by JohanFalt** [comment]
Ok, well that did say something.

You see the "value" under path that are not meant to be there any longer. So my guess is that for some reason as the system tries to update this character it fails and thus it never gets a "version update clearing" which means it keeps trying each time you get a new major version as in the update you set path->value to path->permanent.

So next step.

Can you export that character and send the file to me?
To export it from Foundry you right-click the actor and select "Export Data".

**Comment by JohanFalt** [comment]
Thank you

**Comment by JohanFalt** [comment]
Found it!

There were actually two things that caused this. Each time you upgrade the system and there are a change to the actor's data the actor gets a new version number based on the version that you are updated to. So in this case your character had a version of 2.2.0 which was the latest system version that held a vampire update.

Now when I built this from the beginning I missed to check if the new version and the old version was the same so each time you updated it checked if you had updated to 2.2.0 and the answer was no as the versions was the same and it ran the update one more time. I have removed this so the update only runs ONCE once you have saved it.

Second problem was that regardless if the update had been run or not I recalculated the sheet's path and since that was already done then the value became 0.

So the sheet got updated in 2.2, made it again in 2.3 and put the path to 0, and now again in 3.0 which the same result.

**Comment by rsimmerm** [comment]
Looks like the update to 3.0 reset all my Kindred's humanity.  I'm still on Foundry v10 as I'm not upgrading to v11 yet.

**Comment by JohanFalt** [comment]
It does yes.

**Comment by JohanFalt** [comment]
I’ll see if I can get a 3.0 fix for it.
