### ISSUE TITLE
Era-specific Abilities

### ISSUE THREAD

**Issue by TheFokin** [JohanFalt/Foundry_WoD20#651]
Not all Era-specific abilities (like Ledgermain, Archery, Hearth Wisdom, etc) are in the Abilities list, but instead created as custom Secondary Abilities for all sheets other than Mage.
As a result, you have to press an Era button twice, one is to create the aforementioned Secondary Abilities, another is to make the button visuals change.
However, when you switch back to Modern Era, these Secondary Abilities remain and you have to delete them manually.
Is there a reason why these abilities are not included in the main list? Some of them even have lines in localisation files.

**Comment by JohanFalt** [comment]
Actually the ability list as a whole is a design flaw that is a remain of how I envisioned the system in the beginning. 

In the first version I only thought it would cover Werewolf as that was the game I was playing and from there is slowly grew. And in the beginning I added all abilities to the actor's properties but as I got to Mage that concept broke as there are just too many AND you can add more that aren't listed. So I did a remake of the lists, kept those abilities that are actually listed in each system and threw out the rest marking these as secondary abilities which are Foundry Items.

What I should have done really would have been to move all abilities to Foundry Items but I thought that this way I can keep track on what is a secondary ability and what is a genuine ability.

Enters eras. Suddenly this setup broke again as I didn't want to include those abilities that were listed in the other eras so I create the new abilities as secondary automatically when you enter an era with abilities that doesn't "exist". If you then goes back I have made it so that I don't dare to just throw the abilites away, I just don't as that can cause problem.

Well this is the long reason of why it is as it is. If I had redone the core of the abilities I had created them all as items and that had been simpler :)... I think.

**Comment by TheFokin** [comment]
I see. 
Two questions then.
1. Is it possible to add a "Hide" button for Secondary Abilities? I know that in a normal playthorugh it's very unlikely to switch back and forth between eras, but still.
2. Is it possible to add localisation keys for these Era-specific Secondary abilities at the generation stage?

**Comment by JohanFalt** [comment]
Will add both

**Comment by TheFokin** [comment]
Thanks. Keep up the great work!
