### ISSUE TITLE
Register the different Fonts

### ISSUE THREAD

**Issue by JohanFalt** [JohanFalt/Foundry_WoD20#701]
https://foundryvtt.com/article/v10-font-config/

**Comment by JohanFalt** [comment]
> Perhaps a good time to change the Demon font to the official one? ;)

This is already done. According to the templates of Demon the font spacelvey and wilhelm_klingspor are used, and since spacelvey only uses A-Z in its setup I am using wilhelm_klingspor.

**Comment by Kad-Caiel** [comment]
Not exactly. Spacelvey is a clone of **LushUs**, the official font. 
Space doesn't have accent, nor spanish "ñ", but LushUs yes. The problem is that LushUs use the same capital size letter for upper and lower case, and you need to manually increase the size of the initial letter. If I remember correctly, the size for the core rulebook tittles are 16 for initial and 10 for the rest.
I sent you an updated version with accents in the letter some time ago. I can improve the lowercase with a small size, if needed.
I never seen Wilhelm in a demon sheet, only LushUs and some times Scythe.

**Comment by JohanFalt** [comment]
Doesn't really work as desired, after registered the fonts CSS stops working. Investigates why later.
