### ISSUE TITLE
[[Feature Request]] Expand text boxes

### ISSUE THREAD

**Issue by RinVindor** [JohanFalt/Foundry_WoD20#849]
**Is your feature request related to a problem? Please describe.**
Yes, filling out the boxes in items can be tedious sometimes and at worst a nightmare due to the small size and lack of expandability.
The image below is when its only tedious to fill out. The second image is when it becomes a nightmare, tables have additional options that appear and it makes table usage much nicer sure but at the current size these tables are a struggle to work with.
![image](https://github.com/JohanFalt/Foundry_WoD20/assets/12647469/2e0024ad-3c8e-4954-8b16-3da2dd3713d0)

![image](https://github.com/JohanFalt/Foundry_WoD20/assets/12647469/62146cbd-f3b0-4949-a5e2-90310d48acf1)

**Describe the solution you'd like**
When the item page itself is expanded it'd be great if both the Description and the System sections would both equally increase in size as window is expanded! That'd make it faster but still enable them to remain compact for those who want after they're filled out.

As always thanks for all the hard work!

**Comment by Kad-Caiel** [comment]
There're three or four threads about the same. Take a look before open another :S

But yes, there's a minor problem with this (you can edit in Word, and then, paste).
The problem is about space? Maybe the solution revolves around the empty, unused areas:
![imagen](https://github.com/JohanFalt/Foundry_WoD20/assets/114583468/08b5f0f0-bbcf-442d-a744-7488136c77c2)

Maybe if you can set lvl as two digit box at the left of the tittle, and reference at the very right in the same line... and so with others traits/windows.
